### ISSUE TITLE
Check config file validity.

### ISSUE THREAD

**Issue by xingweitian** [xingweitian/fund-my-watcard#26]
Add a new argument to check the validity of config file.

E.g.,
Name -> can only have letters, can't have numbers, symbols...
Phone number -> need to match the phone number format
Postal code -> need to match the postal code format
...

**Comment by KevinLu** [comment]
I can work on this.

**Comment by KevinLu** [comment]
Do you want this to be a command like 
`py watcard --valid`?

Maybe we can add a function to do the validity test after user creates/edits the config file?

**Comment by xingweitian** [comment]
> Do you want this to be a command like
> `py watcard --valid`?
> 
> Maybe we can add a function to do the validity test after user creates/edits the config file?

Yes, that sounds good. For now, I think it is better to let it be optional. Maybe when error occurs in `watcard --fund`, print a hint, like "please use --valid to check if you write your config file correctly."

**Comment by KevinLu** [comment]
After some thought about this issue and testing the payment form, here are the tests we can do:

  "userName": no special unicode
  "password": anything,
  "ordName": only letters,
  "phoneNumber": 10 numbers,
  "address1": anything,
  "address2": anything,
  "ordPostalCode": proper postal code format,
  "ordCity": letters,
  "ordEmailAddress": proper email format,
  "paymentMethod": check if it's CC,
  "trnCardOwner": only letters,
  "trnCardType": only types specified in README,
  "trnCardNumber": only numbers, maybe use Luhn algorithm?,
  "trnExpMonth": only 2 numbers,
  "trnExpYear": only 2 numbers,
  "trnCardCvd": 3 numbers,

I also noticed this script is only for users living in Ontario since it doesn't specify province and country. Maybe we don't need to worry about international users.

**Comment by faushine** [comment]
How about check JSON validity at the same time? Users may accidentally delete something.

**Comment by KevinLu** [comment]
> 
> 
> How about check JSON validity at the same time? Users may accidentally delete something.

Good idea. We can do that too.
